"""create planet table

Revision ID: 50c82a474cdd
Revises: 
Create Date: 2026-02-07 09:42:44.932491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c82a474cdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo_type',
    sa.Column('cargo_type_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cargo_type_id', name=op.f('pk_cargo_type')),
    sa.UniqueConstraint('name', name=op.f('uq_cargo_type_name')),
    schema='planet'
    )
    op.create_table('sector',
    sa.Column('sector_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sector_id', name=op.f('pk_sector')),
    sa.UniqueConstraint('name', name=op.f('uq_sector_name')),
    schema='planet'
    )
    op.create_table('planet',
    sa.Column('planet_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sector_id', sa.BigInteger(), nullable=False),
    sa.Column('scarce_cargo_type_id', sa.BigInteger(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scarce_cargo_type_id'], ['planet.cargo_type.cargo_type_id'], name=op.f('fk_planet_scarce_cargo_type_id_cargo_type')),
    sa.ForeignKeyConstraint(['sector_id'], ['planet.sector.sector_id'], name=op.f('fk_planet_sector_id_sector')),
    sa.PrimaryKeyConstraint('planet_id', name=op.f('pk_planet')),
    sa.UniqueConstraint('name', name=op.f('uq_planet_name')),
    schema='planet'
    )
    op.create_table('starship',
    sa.Column('starship_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('planet_id', sa.BigInteger(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.planet.planet_id'], name=op.f('fk_starship_planet_id_planet')),
    sa.PrimaryKeyConstraint('starship_id', name=op.f('pk_starship')),
    schema='planet'
    )
    op.create_table('manifest',
    sa.Column('manifest_id', sa.BigInteger(), nullable=False),
    sa.Column('starship_id', sa.BigInteger(), nullable=False),
    sa.Column('cargo_type_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_manifest_ck_manifest_quantity_non_negative')),
    sa.ForeignKeyConstraint(['cargo_type_id'], ['planet.cargo_type.cargo_type_id'], name=op.f('fk_manifest_cargo_type_id_cargo_type')),
    sa.ForeignKeyConstraint(['starship_id'], ['planet.starship.starship_id'], name=op.f('fk_manifest_starship_id_starship')),
    sa.PrimaryKeyConstraint('manifest_id', name=op.f('pk_manifest')),
    sa.UniqueConstraint('starship_id', 'cargo_type_id', name='uq_manifest_starship_cargo'),
    schema='planet'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manifest', schema='planet')
    op.drop_table('starship', schema='planet')
    op.drop_table('planet', schema='planet')
    op.drop_table('sector', schema='planet')
    op.drop_table('cargo_type', schema='planet')
    # ### end Alembic commands ###
